// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Compute a BLAKE3 hash of a file by streaming it in chunks.
///
/// The file is read in 1 MiB blocks and fed incrementally into the hasher, so
/// memory usage stays constant regardless of file size. Runs on the
/// flutter_rust_bridge thread pool, so it does not block the UI.
///
/// Returns the 64-char lowercase hex digest.
Future<String> blake3HashFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleBlake3HashFile(path: path);
